[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = ["fastapi", "uvicorn", "pandas", "numpy", "pydantic", "python-dotenv", "sqlalchemy", "psycopg2-binary", "alembic", "pydantic-settings"]
